import Head from 'next/head'
import { Inter } from 'next/font/google'
import Autocomplete from '@mui/material/Autocomplete';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  // create a list of 6 objects within a name as string and an array of 3 random numbers each for demo purpose
  const options = Array.from(Array(6), (_, i) => ({ name: `Option ${i + 1}`, random: Array.from(Array(3), () => Math.round(Math.random() * 100)) }));
  console.log(options);
  let randomValue = null;
  const defaultProps = {
    options: options.map((option) => option.name),
    getOptionLabel: (option: string) => option,
  };
  function getRandom(value: string){
    const random = options.find((option) => option.name === value)?.random;
    randomValue = random;
    console.log(randomValue);
  }
  return (
    <>
      <Head>
        <title>Bootcraft.Class</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="MAIN">
      <h1>ENTREGAS</h1>
      </main>
    </>
  )
}
