import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Autocomplete from '@mui/material/Autocomplete';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
// CREATE A LIST of 10 names for demo purposes
const options = [ 'John', 'Paul', 'George', 'Ringo', 'Pete', 'Stuart', 'Mick', 'Keith', 'Ronnie', 'Charlie' ] 
  const defaultProps = {
    options: options,
    getOptionLabel: (option: string) => option,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>ENTREGAS</h1>
      <Stack spacing={1} sx={{ width: 400 }}>
        <Autocomplete
          {...defaultProps}
          id="auto-complete"
          autoComplete
          includeInputInList
          renderInput={(params) => (
            <TextField {...params} label="autoComplete" variant="standard" />
          )}
      />
      </Stack>
      </main>
    </>
  )
}
